const POSES = [
  // Standing
  { id: 'tadasana',            english: 'Mountain Pose',           sanskrit: 'Tadasana',                   category: 'Standing' },
  { id: 'virabhadrasana-i',    english: 'Warrior I',               sanskrit: 'Virabhadrasana I',            category: 'Standing',
    aliases: ['Warrior 1', 'Warrior One'] },
  { id: 'virabhadrasana-ii',   english: 'Warrior II',              sanskrit: 'Virabhadrasana II',           category: 'Standing',
    aliases: ['Warrior 2', 'Warrior Two'] },
  { id: 'virabhadrasana-iii',  english: 'Warrior III',             sanskrit: 'Virabhadrasana III',          category: 'Standing',
    aliases: ['Warrior 3', 'Warrior Three'] },
  { id: 'trikonasana',         english: 'Triangle Pose',           sanskrit: 'Trikonasana',                 category: 'Standing',
    aliases: ['Triangle'] },
  { id: 'parsvakonasana',      english: 'Extended Side Angle',     sanskrit: 'Utthita Parsvakonasana',      category: 'Standing',
    aliases: ['Extended Side Angle Pose', 'Side Angle Pose', 'Side Angle'] },
  { id: 'vrikshasana',         english: 'Tree Pose',               sanskrit: 'Vrikshasana',                 category: 'Standing',
    aliases: ['Tree'] },
  { id: 'utkatasana',          english: 'Chair Pose',              sanskrit: 'Utkatasana',                  category: 'Standing',
    aliases: ['Chair'] },
  { id: 'uttanasana',          english: 'Standing Forward Fold',   sanskrit: 'Uttanasana',                  category: 'Standing',
    aliases: ['Standing Forward Bend', 'Forward Fold', 'Forward Bend'] },
  { id: 'ardha-chandrasana',   english: 'Half Moon Pose',          sanskrit: 'Ardha Chandrasana',           category: 'Standing',
    aliases: ['Half Moon'] },
  // Seated
  { id: 'dandasana',           english: 'Staff Pose',              sanskrit: 'Dandasana',                   category: 'Seated'   },
  { id: 'paschimottanasana',   english: 'Seated Forward Fold',     sanskrit: 'Paschimottanasana',           category: 'Seated',
    aliases: ['Seated Forward Bend'] },
  { id: 'sukhasana',           english: 'Easy Pose',               sanskrit: 'Sukhasana',                   category: 'Seated'   },
  { id: 'padmasana',           english: 'Lotus Pose',              sanskrit: 'Padmasana',                   category: 'Seated',
    aliases: ['Lotus'] },
  { id: 'baddha-konasana',     english: 'Butterfly Pose',          sanskrit: 'Baddha Konasana',             category: 'Seated',
    aliases: ['Bound Angle Pose', 'Bound Angle', "Cobbler's Pose"] },
  { id: 'navasana',            english: 'Boat Pose',               sanskrit: 'Navasana',                    category: 'Seated',
    aliases: ['Boat'] },
  { id: 'virasana',            english: 'Hero Pose',               sanskrit: 'Virasana',                    category: 'Seated',
    aliases: ['Hero'] },
  // Supine
  { id: 'savasana',            english: 'Corpse Pose',             sanskrit: 'Savasana',                    category: 'Supine',
    aliases: ['Corpse', 'Savasana'] },
  { id: 'ananda-balasana',     english: 'Happy Baby',              sanskrit: 'Ananda Balasana',             category: 'Supine',
    aliases: ['Happy Baby Pose'] },
  { id: 'setu-bandha',         english: 'Bridge Pose',             sanskrit: 'Setu Bandha Sarvangasana',    category: 'Supine',
    aliases: ['Bridge'] },
  // Prone
  { id: 'bhujangasana',        english: 'Cobra Pose',              sanskrit: 'Bhujangasana',                category: 'Prone',
    aliases: ['Cobra'] },
  { id: 'urdhva-mukha',        english: 'Upward Dog',              sanskrit: 'Urdhva Mukha Svanasana',      category: 'Prone',
    aliases: ['Upward Facing Dog', 'Upward-Facing Dog'] },
  { id: 'balasana',            english: "Child's Pose",            sanskrit: 'Balasana',                    category: 'Prone',
    aliases: ['Child Pose', 'Childs Pose'] },
  { id: 'salabhasana',         english: 'Locust Pose',             sanskrit: 'Salabhasana',                 category: 'Prone',
    aliases: ['Locust'] },
  // Backbend
  { id: 'urdhva-dhanurasana',  english: 'Wheel Pose',              sanskrit: 'Urdhva Dhanurasana',          category: 'Backbend',
    aliases: ['Wheel', 'Upward Bow Pose', 'Upward Bow'] },
  { id: 'ustrasana',           english: 'Camel Pose',              sanskrit: 'Ustrasana',                   category: 'Backbend',
    aliases: ['Camel'] },
  // Inversion
  { id: 'adho-mukha',          english: 'Downward Dog',            sanskrit: 'Adho Mukha Svanasana',        category: 'Inversion',
    aliases: ['Downward Facing Dog', 'Downward-Facing Dog', 'Down Dog'] },
  { id: 'sirsasana',           english: 'Headstand',               sanskrit: 'Sirsasana',                   category: 'Inversion',
    aliases: ['Head Stand'] },
  { id: 'sarvangasana',        english: 'Shoulder Stand',          sanskrit: 'Sarvangasana',                category: 'Inversion',
    aliases: ['Shoulder Stand Pose', 'Shoulderstand'] },
  // Twist
  { id: 'ardha-matsyendrasana',english: 'Half Lord of the Fishes', sanskrit: 'Ardha Matsyendrasana',        category: 'Twist',
    aliases: ['Half Lord of the Fishes Pose', 'Seated Spinal Twist', 'Half Spinal Twist'] },
];
