const POSES = [
  // Standing
  { id: 'tadasana',            english: 'Mountain Pose',           sanskrit: 'Tadasana',                   category: 'Standing',
    pronunciation: 'tah · DAH · sah · nah' },
  { id: 'virabhadrasana-i',    english: 'Warrior I',               sanskrit: 'Virabhadrasana I',            category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 1', 'Warrior One'] },
  { id: 'virabhadrasana-ii',   english: 'Warrior II',              sanskrit: 'Virabhadrasana II',           category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 2', 'Warrior Two'] },
  { id: 'virabhadrasana-iii',  english: 'Warrior III',             sanskrit: 'Virabhadrasana III',          category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 3', 'Warrior Three'] },
  { id: 'trikonasana',         english: 'Triangle Pose',           sanskrit: 'Trikonasana',                 category: 'Standing',
    pronunciation: 'tree · koh · NAH · sah · nah',
    aliases: ['Triangle'] },
  { id: 'parsvakonasana',      english: 'Extended Side Angle',     sanskrit: 'Utthita Parsvakonasana',      category: 'Standing',
    pronunciation: 'oo · TEE · tah · parsh · vah · koh · NAH · sah · nah',
    aliases: ['Extended Side Angle Pose', 'Side Angle Pose', 'Side Angle'] },
  { id: 'vrikshasana',         english: 'Tree Pose',               sanskrit: 'Vrikshasana',                 category: 'Standing',
    pronunciation: 'vrik · SHAH · sah · nah',
    aliases: ['Tree'] },
  { id: 'utkatasana',          english: 'Chair Pose',              sanskrit: 'Utkatasana',                  category: 'Standing',
    pronunciation: 'oot · kah · TAH · sah · nah',
    aliases: ['Chair'] },
  { id: 'uttanasana',          english: 'Standing Forward Fold',   sanskrit: 'Uttanasana',                  category: 'Standing',
    pronunciation: 'oot · tah · NAH · sah · nah',
    aliases: ['Standing Forward Bend', 'Forward Fold', 'Forward Bend'] },
  { id: 'ardha-chandrasana',   english: 'Half Moon Pose',          sanskrit: 'Ardha Chandrasana',           category: 'Standing',
    pronunciation: 'AR · dah · chan · DRAH · sah · nah',
    aliases: ['Half Moon'] },
  { id: 'garudasana',          english: 'Eagle Pose',              sanskrit: 'Garudasana',                  category: 'Standing',
    pronunciation: 'gah · roo · DAH · sah · nah',
    aliases: ['Eagle'] },
  { id: 'viparita-virabhadrasana', english: 'Reverse Warrior',     sanskrit: 'Viparita Virabhadrasana',     category: 'Standing',
    pronunciation: 'vih · pah · REE · tah · veer · ah · bah · DRAH · sah · nah',
    aliases: ['Reverse Warrior Pose'] },
  { id: 'prasarita-padottanasana', english: 'Wide-Legged Forward Fold', sanskrit: 'Prasarita Padottanasana', category: 'Standing',
    pronunciation: 'prah · sah · REE · tah · pah · doh · tah · NAH · sah · nah',
    aliases: ['Wide Legged Forward Fold', 'Wide-Legged Forward Bend'] },
  { id: 'natarajasana',          english: "Dancer's Pose",            sanskrit: 'Natarajasana',                category: 'Standing',
    pronunciation: 'nah · tah · RAH · jah · sah · nah',
    aliases: ['Lord of the Dance Pose', 'King Dancer Pose'] },
  { id: 'parsvottanasana',       english: 'Pyramid Pose',             sanskrit: 'Parsvottanasana',             category: 'Standing',
    pronunciation: 'parsh · voh · tah · NAH · sah · nah',
    aliases: ['Pyramid', 'Intense Side Stretch'] },
  { id: 'parivrtta-trikonasana', english: 'Revolved Triangle',        sanskrit: 'Parivrtta Trikonasana',       category: 'Standing',
    pronunciation: 'pah · rih · VRIT · tah · tree · koh · NAH · sah · nah',
    aliases: ['Revolved Triangle Pose', 'Twisted Triangle'] },
  // Seated
  { id: 'dandasana',           english: 'Staff Pose',              sanskrit: 'Dandasana',                   category: 'Seated',
    pronunciation: 'dan · DAH · sah · nah' },
  { id: 'paschimottanasana',   english: 'Seated Forward Fold',     sanskrit: 'Paschimottanasana',           category: 'Seated',
    pronunciation: 'pash · ee · moh · tah · NAH · sah · nah',
    aliases: ['Seated Forward Bend'] },
  { id: 'sukhasana',           english: 'Easy Pose',               sanskrit: 'Sukhasana',                   category: 'Seated',
    pronunciation: 'soo · KAH · sah · nah' },
  { id: 'padmasana',           english: 'Lotus Pose',              sanskrit: 'Padmasana',                   category: 'Seated',
    pronunciation: 'pad · MAH · sah · nah',
    aliases: ['Lotus'] },
  { id: 'baddha-konasana',     english: 'Butterfly Pose',          sanskrit: 'Baddha Konasana',             category: 'Seated',
    pronunciation: 'BAH · dah · koh · NAH · sah · nah',
    aliases: ['Bound Angle Pose', 'Bound Angle', "Cobbler's Pose"] },
  { id: 'navasana',            english: 'Boat Pose',               sanskrit: 'Navasana',                    category: 'Seated',
    pronunciation: 'nah · VAH · sah · nah',
    aliases: ['Boat'] },
  { id: 'virasana',            english: 'Hero Pose',               sanskrit: 'Virasana',                    category: 'Seated',
    pronunciation: 'veer · AH · sah · nah',
    aliases: ['Hero'] },
  { id: 'janu-sirsasana',      english: 'Head-to-Knee Pose',       sanskrit: 'Janu Sirsasana',              category: 'Seated',
    pronunciation: 'JAH · noo · sheer · SHAH · sah · nah',
    aliases: ['Head to Knee Pose', 'Head to Knee Forward Bend'] },
  { id: 'gomukhasana',         english: 'Cow Face Pose',           sanskrit: 'Gomukhasana',                 category: 'Seated',
    pronunciation: 'go · moo · KAH · sah · nah',
    aliases: ['Cow Face'] },
  { id: 'upavistha-konasana',  english: 'Wide-Angle Seated Forward Fold', sanskrit: 'Upavistha Konasana',    category: 'Seated',
    pronunciation: 'oo · pah · VISH · tah · koh · NAH · sah · nah',
    aliases: ['Wide Angle Seated Forward Fold', 'Wide-Angle Forward Bend'] },
  // Supine
  { id: 'savasana',            english: 'Corpse Pose',             sanskrit: 'Savasana',                    category: 'Supine',
    pronunciation: 'shah · VAH · sah · nah',
    aliases: ['Corpse', 'Savasana'] },
  { id: 'ananda-balasana',     english: 'Happy Baby',              sanskrit: 'Ananda Balasana',             category: 'Supine',
    pronunciation: 'ah · NAN · dah · bah · LAH · sah · nah',
    aliases: ['Happy Baby Pose'] },
  { id: 'setu-bandha',         english: 'Bridge Pose',             sanskrit: 'Setu Bandha Sarvangasana',    category: 'Supine',
    pronunciation: 'SAY · too · BAN · dah · sar · van · GAH · sah · nah',
    aliases: ['Bridge'] },
  { id: 'supta-baddha-konasana', english: 'Reclining Bound Angle', sanskrit: 'Supta Baddha Konasana',       category: 'Supine',
    pronunciation: 'SOOP · tah · BAH · dah · koh · NAH · sah · nah',
    aliases: ['Reclining Bound Angle Pose', 'Reclined Butterfly'] },
  { id: 'matsyasana',          english: 'Fish Pose',               sanskrit: 'Matsyasana',                  category: 'Supine',
    pronunciation: 'maht · SYAH · sah · nah',
    aliases: ['Fish'] },
  { id: 'supta-padangusthasana', english: 'Reclining Hand-to-Big-Toe Pose', sanskrit: 'Supta Padangusthasana', category: 'Supine',
    pronunciation: 'SOOP · tah · pah · dan · goosh · TAH · sah · nah',
    aliases: ['Reclining Hand to Big Toe Pose', 'Reclined Hand to Toe'] },
  // Prone
  { id: 'bhujangasana',        english: 'Cobra Pose',              sanskrit: 'Bhujangasana',                category: 'Prone',
    pronunciation: 'boo · jan · GAH · sah · nah',
    aliases: ['Cobra'] },
  { id: 'urdhva-mukha',        english: 'Upward Dog',              sanskrit: 'Urdhva Mukha Svanasana',      category: 'Prone',
    pronunciation: 'OORD · vah · MOO · kah · svah · NAH · sah · nah',
    aliases: ['Upward Facing Dog', 'Upward-Facing Dog'] },
  { id: 'balasana',            english: "Child's Pose",            sanskrit: 'Balasana',                    category: 'Prone',
    pronunciation: 'bah · LAH · sah · nah',
    aliases: ['Child Pose', 'Childs Pose'] },
  { id: 'salabhasana',         english: 'Locust Pose',             sanskrit: 'Salabhasana',                 category: 'Prone',
    pronunciation: 'shah · lah · BAH · sah · nah',
    aliases: ['Locust'] },
  { id: 'dhanurasana',         english: 'Bow Pose',                sanskrit: 'Dhanurasana',                 category: 'Prone',
    pronunciation: 'dah · noo · RAH · sah · nah',
    aliases: ['Bow'] },
  // Backbend
  { id: 'urdhva-dhanurasana',  english: 'Wheel Pose',              sanskrit: 'Urdhva Dhanurasana',          category: 'Backbend',
    pronunciation: 'OORD · vah · dah · noo · RAH · sah · nah',
    aliases: ['Wheel', 'Upward Bow Pose', 'Upward Bow'] },
  { id: 'ustrasana',           english: 'Camel Pose',              sanskrit: 'Ustrasana',                   category: 'Backbend',
    pronunciation: 'oos · TRAH · sah · nah',
    aliases: ['Camel'] },
  // Inversion
  { id: 'adho-mukha',          english: 'Downward Dog',            sanskrit: 'Adho Mukha Svanasana',        category: 'Inversion',
    pronunciation: 'AH · doh · MOO · kah · svah · NAH · sah · nah',
    aliases: ['Downward Facing Dog', 'Downward-Facing Dog', 'Down Dog'] },
  { id: 'sirsasana',           english: 'Headstand',               sanskrit: 'Sirsasana',                   category: 'Inversion',
    pronunciation: 'sheer · SHAH · sah · nah',
    aliases: ['Head Stand'] },
  { id: 'sarvangasana',        english: 'Shoulder Stand',          sanskrit: 'Sarvangasana',                category: 'Inversion',
    pronunciation: 'sar · van · GAH · sah · nah',
    aliases: ['Shoulder Stand Pose', 'Shoulderstand'] },
  { id: 'halasana',            english: 'Plow Pose',               sanskrit: 'Halasana',                    category: 'Inversion',
    pronunciation: 'hah · LAH · sah · nah',
    aliases: ['Plow'] },
  { id: 'adho-mukha-vrksasana', english: 'Handstand',              sanskrit: 'Adho Mukha Vrksasana',        category: 'Inversion',
    pronunciation: 'AH · doh · MOO · kah · vrk · SHAH · sah · nah',
    aliases: ['Hand Stand'] },
  { id: 'pincha-mayurasana',   english: 'Forearm Stand',           sanskrit: 'Pincha Mayurasana',           category: 'Inversion',
    pronunciation: 'pin · chah · mah · yoo · RAH · sah · nah',
    aliases: ['Feathered Peacock Pose', 'Forearm Balance'] },
  { id: 'viparita-karani',     english: 'Legs Up the Wall',        sanskrit: 'Viparita Karani',             category: 'Inversion',
    pronunciation: 'vih · pah · REE · tah · kah · RAH · nee',
    aliases: ['Legs Up the Wall Pose'] },
  // Twist
  { id: 'ardha-matsyendrasana',english: 'Half Lord of the Fishes', sanskrit: 'Ardha Matsyendrasana',        category: 'Twist',
    pronunciation: 'AR · dah · maht · syen · DRAH · sah · nah',
    aliases: ['Half Lord of the Fishes Pose', 'Seated Spinal Twist', 'Half Spinal Twist'] },
  { id: 'marichyasana',        english: "Marichi's Pose",          sanskrit: 'Marichyasana',                category: 'Twist',
    pronunciation: 'mah · ree · CHYAH · sah · nah',
    aliases: ['Marichi Pose', 'Sage Marichi Pose'] },
  // Arm Balance
  { id: 'bakasana',            english: 'Crow Pose',               sanskrit: 'Bakasana',                    category: 'Arm Balance',
    pronunciation: 'bah · KAH · sah · nah',
    aliases: ['Crow', 'Crane Pose'] },
  { id: 'vasisthasana',        english: 'Side Plank',              sanskrit: 'Vasisthasana',                category: 'Arm Balance',
    pronunciation: 'vah · sish · TAH · sah · nah',
    aliases: ['Side Plank Pose'] },
  { id: 'chaturanga-dandasana',english: 'Four-Limbed Staff Pose',  sanskrit: 'Chaturanga Dandasana',        category: 'Arm Balance',
    pronunciation: 'chah · too · RAHN · gah · dan · DAH · sah · nah',
    aliases: ['Low Plank', 'Chaturanga'] },
  // Hip Opener
  { id: 'hanumanasana',        english: 'Splits',                  sanskrit: 'Hanumanasana',                category: 'Hip Opener',
    pronunciation: 'hah · noo · mah · NAH · sah · nah',
    aliases: ['Monkey Pose', 'Monkey'] },
  { id: 'eka-pada-rajakapotasana', english: 'Pigeon Pose',         sanskrit: 'Eka Pada Rajakapotasana',     category: 'Hip Opener',
    pronunciation: 'eh · kah · PAH · dah · rah · jah · kah · poh · TAH · sah · nah',
    aliases: ['One-Legged King Pigeon', 'Pigeon'] },
];
