const POSES = [
  // Standing
  { id: 'tadasana',            english: 'Mountain Pose',           sanskrit: 'Tadasana',                   category: 'Standing',
    pronunciation: 'tah · DAH · sah · nah',
    description: 'The foundational standing pose - feet grounded, legs active, spine long, and the whole body organised in neutral alignment.' },
  { id: 'virabhadrasana-i',    english: 'Warrior I',               sanskrit: 'Virabhadrasana I',            category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 1', 'Warrior One'],
    description: 'A standing lunge with arms raised overhead, requiring the hips to square toward the front while the back foot roots firmly at 45°.' },
  { id: 'virabhadrasana-ii',   english: 'Warrior II',              sanskrit: 'Virabhadrasana II',           category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 2', 'Warrior Two'],
    description: 'A wide-legged stance with the front knee bent over the ankle, hips open to the long edge of the mat, and arms extending in opposite directions.' },
  { id: 'virabhadrasana-iii',  english: 'Warrior III',             sanskrit: 'Virabhadrasana III',          category: 'Standing',
    pronunciation: 'veer · ah · bah · DRAH · sah · nah',
    aliases: ['Warrior 3', 'Warrior Three'],
    description: 'A single-leg balance with the torso and lifted leg forming one long horizontal line from heel to fingertips.' },
  { id: 'trikonasana',         english: 'Triangle Pose',           sanskrit: 'Trikonasana',                 category: 'Standing',
    pronunciation: 'tree · koh · NAH · sah · nah',
    aliases: ['Triangle'],
    description: 'A wide-legged lateral stretch with straight legs, the torso extending over the front leg and both arms stacking vertically.' },
  { id: 'parsvakonasana',      english: 'Extended Side Angle',     sanskrit: 'Utthita Parsvakonasana',      category: 'Standing',
    pronunciation: 'oo · TEE · tah · parsh · vah · koh · NAH · sah · nah',
    aliases: ['Extended Side Angle Pose', 'Side Angle Pose', 'Side Angle'],
    description: 'A deep side stretch in a wide-legged lunge, the body creating one diagonal line from back foot through the extended top arm.' },
  { id: 'vrikshasana',         english: 'Tree Pose',               sanskrit: 'Vrikshasana',                 category: 'Standing',
    pronunciation: 'vrik · SHAH · sah · nah',
    aliases: ['Tree'],
    description: 'A one-legged balance with the raised foot pressing into the inner thigh or calf, hips level, and the spine growing tall.' },
  { id: 'utkatasana',          english: 'Chair Pose',              sanskrit: 'Utkatasana',                  category: 'Standing',
    pronunciation: 'oot · kah · TAH · sah · nah',
    aliases: ['Chair'],
    description: 'A powerful squatting stance with thighs angling toward the floor, demanding equal strength in the legs and length through the spine.' },
  { id: 'uttanasana',          english: 'Standing Forward Fold',   sanskrit: 'Uttanasana',                  category: 'Standing',
    pronunciation: 'oot · tah · NAH · sah · nah',
    aliases: ['Standing Forward Bend', 'Forward Fold', 'Forward Bend'],
    description: 'A standing forward fold from the hip crease, with the crown of the head releasing toward the floor and weight shifting slightly forward in the feet.' },
  { id: 'ardha-chandrasana',   english: 'Half Moon Pose',          sanskrit: 'Ardha Chandrasana',           category: 'Standing',
    pronunciation: 'AR · dah · chan · DRAH · sah · nah',
    aliases: ['Half Moon'],
    description: 'A lateral balance on one leg and one hand, with the body opening to the side and the lifted leg extending parallel to the floor.' },
  { id: 'garudasana',          english: 'Eagle Pose',              sanskrit: 'Garudasana',                  category: 'Standing',
    pronunciation: 'gah · roo · DAH · sah · nah',
    aliases: ['Eagle'],
    description: 'A standing balance in which both arms and legs cross and wrap, creating compression in the joints and requiring deep focus to maintain.' },
  { id: 'viparita-virabhadrasana', english: 'Reverse Warrior',     sanskrit: 'Viparita Virabhadrasana',     category: 'Standing',
    pronunciation: 'vih · pah · REE · tah · veer · ah · bah · DRAH · sah · nah',
    aliases: ['Reverse Warrior Pose'],
    description: 'From Warrior II, the front arm sweeps up and back into a lateral arch, opening the side body while the legs hold their grounded foundation.' },
  { id: 'prasarita-padottanasana', english: 'Wide-Legged Forward Fold', sanskrit: 'Prasarita Padottanasana', category: 'Standing',
    pronunciation: 'prah · sah · REE · tah · pah · doh · tah · NAH · sah · nah',
    aliases: ['Wide Legged Forward Fold', 'Wide-Legged Forward Bend'],
    description: 'A wide-legged standing forward fold from the hips, with the crown of the head releasing toward or touching the floor between the feet.' },
  { id: 'natarajasana',          english: "Dancer's Pose",            sanskrit: 'Natarajasana',                category: 'Standing',
    pronunciation: 'nah · tah · RAH · jah · sah · nah',
    aliases: ['Lord of the Dance Pose', 'King Dancer Pose'],
    description: 'A standing backbend and balance in which the lifted leg is held from behind, the back leg pressing into the hand to create an expansive arch through the front body.' },
  { id: 'parsvottanasana',       english: 'Pyramid Pose',             sanskrit: 'Parsvottanasana',             category: 'Standing',
    pronunciation: 'parsh · voh · tah · NAH · sah · nah',
    aliases: ['Pyramid', 'Intense Side Stretch'],
    description: 'A narrow-stance intense forward fold over a straight front leg, with both hips squared squarely to the front.' },
  { id: 'parivrtta-trikonasana', english: 'Revolved Triangle',        sanskrit: 'Parivrtta Trikonasana',       category: 'Standing',
    pronunciation: 'pah · rih · VRIT · tah · tree · koh · NAH · sah · nah',
    aliases: ['Revolved Triangle Pose', 'Twisted Triangle'],
    description: 'A standing twist over a straight front leg, with the opposite hand grounding beside the foot and the spine rotating fully open.' },
  { id: 'anjaneyasana',          english: 'Low Lunge',               sanskrit: 'Anjaneyasana',                category: 'Standing',
    pronunciation: 'an · jah · nay · AH · sah · nah',
    aliases: ['Low Lunge Pose', 'Crescent Lunge'],
    description: 'A kneeling lunge with the back knee down, hips sinking toward the floor, and arms lifting overhead to open the front of the hip and chest.' },
  { id: 'parivrtta-parsvakonasana', english: 'Revolved Side Angle',  sanskrit: 'Parivrtta Parsvakonasana',    category: 'Standing',
    pronunciation: 'pah · rih · VRIT · tah · parsh · vah · koh · NAH · sah · nah',
    aliases: ['Revolved Side Angle Pose', 'Twisted Side Angle'],
    description: 'A deep standing twist in a lunge, with the opposite elbow hooking outside the front knee to create maximum spinal rotation.' },
  { id: 'parighasana',           english: 'Gate Pose',               sanskrit: 'Parighasana',                 category: 'Standing',
    pronunciation: 'pah · ree · GAH · sah · nah',
    aliases: ['Gate'],
    description: 'A kneeling lateral stretch with one leg extending to the side, the torso arching over it and the upper arm reaching long overhead.' },
  // Seated
  { id: 'dandasana',           english: 'Staff Pose',              sanskrit: 'Dandasana',                   category: 'Seated',
    pronunciation: 'dan · DAH · sah · nah',
    description: 'The seated equivalent of Tadasana - both legs extended, spine vertical, and the hands pressing into the floor beside the hips to lift and lengthen through the torso.' },
  { id: 'paschimottanasana',   english: 'Seated Forward Fold',     sanskrit: 'Paschimottanasana',           category: 'Seated',
    pronunciation: 'pash · ee · moh · tah · NAH · sah · nah',
    aliases: ['Seated Forward Bend'],
    description: 'A deep forward fold from Dandasana, hinging at the hip crease to extend the spine long over the legs rather than rounding into the back.' },
  { id: 'sukhasana',           english: 'Easy Pose',               sanskrit: 'Sukhasana',                   category: 'Seated',
    pronunciation: 'soo · KAH · sah · nah',
    description: 'A simple cross-legged seat with the shins loosely crossed, hips elevated enough to allow the pelvis to tilt slightly forward and the spine to rise naturally.' },
  { id: 'padmasana',           english: 'Lotus Pose',              sanskrit: 'Padmasana',                   category: 'Seated',
    pronunciation: 'pad · MAH · sah · nah',
    aliases: ['Lotus'],
    description: 'A deeply meditative seated posture in which each foot rests on the opposite thigh, requiring significant external rotation in both hip joints before the knees can release toward the floor.' },
  { id: 'baddha-konasana',     english: 'Bound Angle Pose',        sanskrit: 'Baddha Konasana',             category: 'Seated',
    pronunciation: 'BAH · dah · koh · NAH · sah · nah',
    aliases: ['Butterfly Pose', 'Bound Angle', "Cobbler's Pose"],
    description: 'A seated hip opener with the soles of the feet together and the knees releasing out to the sides, the hands holding the feet as the spine lifts tall.' },
  { id: 'navasana',            english: 'Boat Pose',               sanskrit: 'Navasana',                    category: 'Seated',
    pronunciation: 'nah · VAH · sah · nah',
    aliases: ['Boat'],
    description: 'A core-intensive balance on the sitting bones with the legs and torso lifted to form a V-shape, demanding both abdominal strength and spinal extension.' },
  { id: 'virasana',            english: 'Hero Pose',               sanskrit: 'Virasana',                    category: 'Seated',
    pronunciation: 'veer · AH · sah · nah',
    aliases: ['Hero'],
    description: 'A kneeling seat between the feet with the tops of the feet flat on the floor, requiring openness through the knee joints and the fronts of the ankles.' },
  { id: 'janu-sirsasana',      english: 'Head-to-Knee Pose',       sanskrit: 'Janu Sirsasana',              category: 'Seated',
    pronunciation: 'JAH · noo · sheer · SHAH · sah · nah',
    aliases: ['Head to Knee Pose', 'Head to Knee Forward Bend'],
    description: 'An asymmetrical seated forward fold over the extended leg, with the bent knee releasing to the side and the spine rotating slightly toward the straight leg.' },
  { id: 'gomukhasana',         english: 'Cow Face Pose',           sanskrit: 'Gomukhasana',                 category: 'Seated',
    pronunciation: 'go · moo · KAH · sah · nah',
    aliases: ['Cow Face'],
    description: 'A seated pose that stacks one knee directly over the other while one arm reaches overhead and the other wraps behind the back, binding at the fingertips to open the shoulders deeply.' },
  { id: 'upavistha-konasana',  english: 'Wide-Angle Seated Forward Fold', sanskrit: 'Upavistha Konasana',    category: 'Seated',
    pronunciation: 'oo · pah · VISH · tah · koh · NAH · sah · nah',
    aliases: ['Wide Angle Seated Forward Fold', 'Wide-Angle Forward Bend'],
    description: 'A wide-legged seated forward fold with both legs spread to the sides, the torso hinging from the hips to extend long toward the floor between the feet.' },
  // Supine
  { id: 'savasana',            english: 'Corpse Pose',             sanskrit: 'Savasana',                    category: 'Supine',
    pronunciation: 'shah · VAH · sah · nah',
    aliases: ['Corpse', 'Savasana'],
    description: 'Complete supine rest with the body fully relaxed and still - considered one of the most important poses in yoga, as it allows the nervous system to absorb and integrate the practice.' },
  { id: 'ananda-balasana',     english: 'Happy Baby',              sanskrit: 'Ananda Balasana',             category: 'Supine',
    pronunciation: 'ah · NAN · dah · bah · LAH · sah · nah',
    aliases: ['Happy Baby Pose'],
    description: 'A gentle supine hip opener lying on the back with knees drawn toward the armpits and hands holding the outer edges of the feet, allowing the sacrum to release toward the floor.' },
  { id: 'setu-bandha',         english: 'Bridge Pose',             sanskrit: 'Setu Bandha Sarvangasana',    category: 'Supine',
    pronunciation: 'SAY · too · BAN · dah · sar · van · GAH · sah · nah',
    aliases: ['Bridge'],
    description: 'A supine backbend with the feet flat on the floor, hips pressing upward as the shoulders root down and the hands optionally clasp beneath the lifted pelvis.' },
  { id: 'supta-baddha-konasana', english: 'Reclining Bound Angle', sanskrit: 'Supta Baddha Konasana',       category: 'Supine',
    pronunciation: 'SOOP · tah · BAH · dah · koh · NAH · sah · nah',
    aliases: ['Reclining Bound Angle Pose', 'Reclined Butterfly'],
    description: 'A restorative supine hip opener with the soles of the feet together and the knees falling open, the spine long on the floor and the breath free to move into the belly.' },
  { id: 'matsyasana',          english: 'Fish Pose',               sanskrit: 'Matsyasana',                  category: 'Supine',
    pronunciation: 'maht · SYAH · sah · nah',
    aliases: ['Fish'],
    description: 'A supine backbend in which the chest lifts and arches, the crown of the head releasing lightly toward the floor while the legs extend and the elbows press into the ground.' },
  { id: 'supta-virasana',        english: 'Reclining Hero Pose',     sanskrit: 'Supta Virasana',              category: 'Supine',
    pronunciation: 'SOOP · tah · veer · AH · sah · nah',
    aliases: ['Reclining Hero', 'Reclined Hero Pose'],
    description: 'Virasana reclined onto the floor or bolster, creating an intense stretch through the quadriceps and hip flexors - only appropriate when the upright form is already comfortable.' },
  { id: 'supta-padangusthasana', english: 'Reclining Hand-to-Big-Toe Pose', sanskrit: 'Supta Padangusthasana', category: 'Supine',
    pronunciation: 'SOOP · tah · pah · dan · goosh · TAH · sah · nah',
    aliases: ['Reclining Hand to Big Toe Pose', 'Reclined Hand to Toe'],
    description: 'A supine hamstring stretch with one leg extended toward the ceiling, the hand or a strap looped around the big toe, while the opposite leg stays grounded and active.' },
  // Prone
  { id: 'bhujangasana',        english: 'Cobra Pose',              sanskrit: 'Bhujangasana',                category: 'Prone',
    pronunciation: 'boo · jan · GAH · sah · nah',
    aliases: ['Cobra'],
    description: 'A prone backbend in which the hands press lightly into the floor beside the lower ribs, the chest lifts using back-body strength, and the elbows stay close to the sides.' },
  { id: 'urdhva-mukha',        english: 'Upward Dog',              sanskrit: 'Urdhva Mukha Svanasana',      category: 'Prone',
    pronunciation: 'OORD · vah · MOO · kah · svah · NAH · sah · nah',
    aliases: ['Upward Facing Dog', 'Upward-Facing Dog'],
    description: 'A prone backbend with straight arms, the thighs and knees lifted entirely off the floor, the chest pressing forward and up while the tops of the feet root firmly down.' },
  { id: 'balasana',            english: "Child's Pose",            sanskrit: 'Balasana',                    category: 'Prone',
    pronunciation: 'bah · LAH · sah · nah',
    aliases: ['Child Pose', 'Childs Pose'],
    description: 'A resting forward fold from a kneeling position, the hips releasing back toward the heels and the forehead settling toward the floor, offering a gentle release for the spine and hips.' },
  { id: 'salabhasana',         english: 'Locust Pose',             sanskrit: 'Salabhasana',                 category: 'Prone',
    pronunciation: 'shah · lah · BAH · sah · nah',
    aliases: ['Locust'],
    description: 'A prone backbend that strengthens the entire back body - the legs, arms, and chest lift simultaneously off the floor using the posterior chain, with no assistance from the hands.' },
  { id: 'dhanurasana',         english: 'Bow Pose',                sanskrit: 'Dhanurasana',                 category: 'Prone',
    pronunciation: 'dah · noo · RAH · sah · nah',
    aliases: ['Bow'],
    description: 'A deep prone backbend in which the hands reach back to grasp the ankles, the kick of the legs drawing the chest and thighs upward to create the shape of a strung bow.' },
  // Backbend
  { id: 'urdhva-dhanurasana',  english: 'Wheel Pose',              sanskrit: 'Urdhva Dhanurasana',          category: 'Backbend',
    pronunciation: 'OORD · vah · dah · noo · RAH · sah · nah',
    aliases: ['Wheel', 'Upward Bow Pose', 'Upward Bow'],
    description: 'A full backbend with hands and feet on the floor, the arms straight and the chest pressing upward - requiring strength and openness across the shoulders, spine, and hip flexors equally.' },
  { id: 'ustrasana',           english: 'Camel Pose',              sanskrit: 'Ustrasana',                   category: 'Backbend',
    pronunciation: 'oos · TRAH · sah · nah',
    aliases: ['Camel'],
    description: 'A kneeling backbend in which the hands reach back for the heels, the hips press forward over the knees, and the chest opens fully - the neck releasing only once the thoracic spine is well extended.' },
  // Inversion
  { id: 'adho-mukha',          english: 'Downward Dog',            sanskrit: 'Adho Mukha Svanasana',        category: 'Inversion',
    pronunciation: 'AH · doh · MOO · kah · svah · NAH · sah · nah',
    aliases: ['Downward Facing Dog', 'Downward-Facing Dog', 'Down Dog'],
    description: 'An inverted V-shape with hands and feet on the floor, the spine lengthening as the hips lift, and the heels releasing toward the earth - a central transitional and resting pose of vinyasa practice.' },
  { id: 'sirsasana',           english: 'Headstand',               sanskrit: 'Sirsasana',                   category: 'Inversion',
    pronunciation: 'sheer · SHAH · sah · nah',
    aliases: ['Head Stand'],
    description: 'An inversion balanced on the crown of the head and forearms, requiring a strong foundation in the arms and shoulders so the neck bears minimal weight, with the body stacked vertically above.' },
  { id: 'sarvangasana',        english: 'Shoulder Stand',          sanskrit: 'Sarvangasana',                category: 'Inversion',
    pronunciation: 'sar · van · GAH · sah · nah',
    aliases: ['Shoulder Stand Pose', 'Shoulderstand'],
    description: 'A full inversion balanced on the shoulders and upper arms, the hands supporting the back as the legs extend skyward and the chin draws toward the chest in a natural throat lock.' },
  { id: 'halasana',            english: 'Plow Pose',               sanskrit: 'Halasana',                    category: 'Inversion',
    pronunciation: 'hah · LAH · sah · nah',
    aliases: ['Plow'],
    description: 'From Shoulder Stand, the legs lower overhead until the toes touch the floor behind, creating a deep stretch through the entire posterior chain and a calming inversion of the breath.' },
  { id: 'adho-mukha-vrksasana', english: 'Handstand',              sanskrit: 'Adho Mukha Vrksasana',        category: 'Inversion',
    pronunciation: 'AH · doh · MOO · kah · vrk · SHAH · sah · nah',
    aliases: ['Hand Stand'],
    description: 'A full inversion balanced on the hands with the body stacked vertically, demanding shoulder stability, core engagement, and the ability to find stillness while inverted.' },
  { id: 'pincha-mayurasana',   english: 'Forearm Stand',           sanskrit: 'Pincha Mayurasana',           category: 'Inversion',
    pronunciation: 'pin · chah · mah · yoo · RAH · sah · nah',
    aliases: ['Feathered Peacock Pose', 'Forearm Balance'],
    description: 'An inversion balanced on the forearms with the palms flat or hands interlaced, the shoulders stacked over the elbows and the body lifting into a vertical line above.' },
  { id: 'viparita-karani',     english: 'Legs Up the Wall',        sanskrit: 'Viparita Karani',             category: 'Inversion',
    pronunciation: 'vih · pah · REE · tah · kah · RAH · nee',
    aliases: ['Legs Up the Wall Pose'],
    description: 'A restorative inversion with the legs extending up a wall and the pelvis supported on a bolster or the floor, encouraging venous return and a deep settling of the nervous system.' },
  // Twist
  { id: 'ardha-matsyendrasana',english: 'Half Lord of the Fishes', sanskrit: 'Ardha Matsyendrasana',        category: 'Twist',
    pronunciation: 'AR · dah · maht · syen · DRAH · sah · nah',
    aliases: ['Half Lord of the Fishes Pose', 'Seated Spinal Twist', 'Half Spinal Twist'],
    description: 'A seated spinal twist with one leg bent and the foot planted outside the opposite thigh, the torso rotating toward the raised knee as the elbow or arm hooks outside it for leverage.' },
  { id: 'marichyasana',        english: "Marichi's Pose",          sanskrit: 'Marichyasana',                category: 'Seated',
    pronunciation: 'mah · ree · CHYAH · sah · nah',
    aliases: ['Marichi Pose', 'Sage Marichi Pose'],
    description: 'A seated forward fold or twist named after the sage Marichi, typically with one knee bent and the corresponding arm wrapping around the shin to bind - integrating hip, shoulder, and spinal work.' },
  // Arm Balance
  { id: 'bakasana',            english: 'Crane Pose',              sanskrit: 'Bakasana',                    category: 'Arm Balance',
    pronunciation: 'bah · KAH · sah · nah',
    aliases: ['Crow Pose', 'Crow'],
    description: 'An arm balance in which the shins or inner thighs rest on the backs of the upper arms, the weight shifting forward until the feet lift - requiring wrist strength, core engagement, and focus.' },
  { id: 'vasisthasana',        english: 'Side Plank',              sanskrit: 'Vasisthasana',                category: 'Arm Balance',
    pronunciation: 'vah · sish · TAH · sah · nah',
    aliases: ['Side Plank Pose'],
    description: 'A lateral arm balance on one hand with the body in one straight line from heel to crown, the top arm extending upward and the obliques working to prevent the hips from dropping.' },
  { id: 'chaturanga-dandasana',english: 'Four-Limbed Staff Pose',  sanskrit: 'Chaturanga Dandasana',        category: 'Arm Balance',
    pronunciation: 'chah · too · RAHN · gah · dan · DAH · sah · nah',
    aliases: ['Low Plank', 'Chaturanga'],
    description: 'A low plank position with the elbows bent to 90° and hugged close to the ribs, the body forming a single horizontal line - the transitional pose between Plank and Upward Dog in a vinyasa.' },
  // Hip Opener
  { id: 'hanumanasana',        english: 'Splits',                  sanskrit: 'Hanumanasana',                category: 'Hip Opener',
    pronunciation: 'hah · noo · mah · NAH · sah · nah',
    aliases: ['Monkey Pose', 'Monkey'],
    description: 'A full front split named after the god Hanuman, requiring complete openness in both the front-leg hamstrings and the back-leg hip flexors, with the pelvis squared and level throughout.' },
  { id: 'malasana',              english: 'Garland Pose',            sanskrit: 'Malasana',                    category: 'Hip Opener',
    pronunciation: 'mah · LAH · sah · nah',
    aliases: ['Squat Pose', 'Yogi Squat'],
    description: 'A deep squat with the feet close together and heels on the floor if possible, the elbows pressing the inner knees wide and the hands in prayer at the chest to lift and open the torso.' },
  { id: 'eka-pada-rajakapotasana', english: 'Pigeon Pose',         sanskrit: 'Eka Pada Rajakapotasana',     category: 'Hip Opener',
    pronunciation: 'eh · kah · PAH · dah · rah · jah · kah · poh · TAH · sah · nah',
    aliases: ['One-Legged King Pigeon', 'Pigeon'],
    description: 'A deep hip opener with the front shin on the floor and the back leg extended behind, targeting the outer hip of the front leg and the hip flexor of the back - the upright version adds a deep backbend.' },
];
